Added debugging output and error handling

diff --git a/.github/workflows/docker-desktop.yml b/.github/workflows/docker-desktop.yml
--- a/.github/workflows/docker-desktop.yml
+++ b/.github/workflows/docker-desktop.yml
@@ -44,6 +44,11 @@ jobs:
             | head -n 1 \
             | sed -E 's/^.+version="([^"]+)".+$/\1/'
         )"
+        if test -z "${VERSION}"; then
+            echo "Failed to fetch latest tag and extract version from GitHub"
+            exit 1
+        fi
+        echo "Got version <${VERSION}>"
 
         echo "version=${VERSION}" >>${GITHUB_OUTPUT}
 
diff --git a/.github/workflows/namespace.yml b/.github/workflows/namespace.yml
--- a/.github/workflows/namespace.yml
+++ b/.github/workflows/namespace.yml
@@ -41,6 +41,11 @@ jobs:
             | grep version \
             | cut -d'"' -f2
         )"
+        if test -z "${VERSION}"; then
+            echo "Failed to fetch latest tag and extract version from GitHub"
+            exit 1
+        fi
+        echo "Got version <${VERSION}>"
 
         echo "version=${VERSION}" >>${GITHUB_OUTPUT}
 
diff --git a/.github/workflows/nodejs-lts.yml b/.github/workflows/nodejs-lts.yml
--- a/.github/workflows/nodejs-lts.yml
+++ b/.github/workflows/nodejs-lts.yml
@@ -40,6 +40,10 @@ jobs:
             curl --silent --location --fail https://github.com/nodejs/Release/raw/main/schedule.json \
             | jq -r 'to_entries[] | select(.value.maintenance > (now | todate)) | select(.value.lts != null) | select(.value.lts < (now | todate)) | .key'
         )"
+        if test -z "${MAJOR_VERSION}"; then
+            echo "Failed to fetch latest tag and extract major version from release schedule"
+            exit 1
+        fi
         echo "### Found LTS major version ${MAJOR_VERSION}"
 
         VERSION="$(
@@ -48,6 +52,10 @@ jobs:
             | cut -f2 | cut -d/ -f3 | tr -d v \
             | sort -Vr | head -1
         )"
+        if test -z "${VERSION}"; then
+            echo "Failed to fetch tag and extract version from GitHub"
+            exit 1
+        fi
         echo "### Found LTS version ${VERSION}"
 
         echo "version=${VERSION}" >>${GITHUB_OUTPUT}
diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -49,6 +49,11 @@ jobs:
             | sort -Vr \
             | head -n 1
         )"
+        if test -z "${VERSION}"; then
+            echo "Failed to fetch latest tag and extract version from GitHub"
+            exit 1
+        fi
+        echo "Got version <${VERSION}>"
 
         echo "version=${VERSION}.${INDYGREG_PYTHON_BUILD_STANDALONE_VERSION}" >>${GITHUB_OUTPUT}
 
