Some fixes

diff --git a/.github/workflows/docker-desktop.yml b/.github/workflows/docker-desktop.yml
--- a/.github/workflows/docker-desktop.yml
+++ b/.github/workflows/docker-desktop.yml
@@ -130,16 +130,22 @@ jobs:
 
         target="${1:-/usr/local}"
         : "${docker_desktop_version:=4.29.0}"
-        build="$(
+        echo "Using Docker Desktop version ${docker_desktop_version}"
+        docker_desktop_build="$(
             curl --silent --show-error --location --fail "https://github.com/docker/docs/raw/main/content/desktop/release-notes.md" \
             | grep "{{< desktop-install all=true version=\"${docker_desktop_version}\" " \
             | sed -E 's|^.+build_path="/([0-9]+)/".+$|\1|'
         )"
+        if test -z "${docker_desktop_build}"; then
+            echo "Failed to find build for Docker Desktop version ${docker_desktop_version}"
+            exit 1
+        fi
+        echo "Using Docker Desktop version ${docker_desktop_version} build ${docker_desktop_build}"
 
         TEMP_DIR="$(mktemp -d)"
         trap "rm -rf ${TEMP_DIR}" EXIT
 
-        curl --location --fail --output "${TEMP_DIR}/docker-desktop-${docker_desktop_version}-amd64.deb" "https://desktop.docker.com/linux/main/amd64/${build}/docker-desktop-${docker_desktop_version}-amd64.deb"
+        curl --location --fail --output "${TEMP_DIR}/docker-desktop-${docker_desktop_version}-amd64.deb" "https://desktop.docker.com/linux/main/amd64/${docker_desktop_build}/docker-desktop-${docker_desktop_version}-amd64.deb"
         ar -x "${TEMP_DIR}/docker-desktop-${docker_desktop_version}-amd64.deb" data.tar.xz --output "${TEMP_DIR}"
         rm "${TEMP_DIR}/docker-desktop-${docker_desktop_version}-amd64.deb"
 
@@ -152,7 +158,7 @@ jobs:
     - name: Install tool
       run: |
         cat ./helper/usr/local/bin/install-docker-debug.sh
-        VERSION="{{ needs.desktop.outputs.version }}" bash -x -e ./helper/usr/local/bin/install-docker-debug.sh .
+        docker_desktop_version="{{ needs.desktop.outputs.version }}" bash -x -e ./helper/usr/local/bin/install-docker-debug.sh .
         find . -type f
 
     - name: Fetch version
